version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile  # Ensure you have a Dockerfile in the nginx directory
    image: "ghcr.io/husnain6666/dilpasand-nginx:${TAG:-latest}"
    ports:
      - "3008:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - client
      - server
    restart: always
    networks:
      - dilpasandnet

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: "ghcr.io/husnain6666/dilpasand-client:${TAG:-latest}"
    networks:
      - dilpasandnet
    restart: unless-stopped


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "ghcr.io/husnain6666/dilpasand-server:${TAG:-latest}"
    networks:
      - dilpasandnet
    restart: always
    environment:
      - NODE_ENV=production  # Set environment directly here
    env_file:
      - ./server/.env

networks:
  dilpasandnet:
    driver: bridge
