import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/ui/footer";
import ModalWrapper from "@/components/context/modalWrapper";

const gillSans = localFont({
  src: "../../public/fonts/Gill Sans Light.otf",
  variable: "--font-paragraph",
  weight: "400",
  style: "normal",
  display: "swap",
});
const futuraBold = localFont({
  src: "../../public/fonts/Futura Book.ttf",
  variable: "--font-heading",
  weight: "700",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Dilpasand",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gillSans.variable} ${futuraBold.variable} antialiased`}
      >
        <ModalWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
