import localFont from "next/font/local";
import "./globals.css";

// Gill Sans for paragraphs
const gillSans = localFont({
  src: "../../public/fonts/Gill Sans Light.otf",
  variable: "--font-paragraph",
  weight: "300",
  style: "normal",
  display: "swap",
});

// Futura Bold for headings
const futuraBold = localFont({
  src: "../../public/fonts/Futura Book.ttf",
  variable: "--font-heading",
  weight: "700",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Dilpasand",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gillSans.variable} ${futuraBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
