import localFont from "next/font/local";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const customFont = localFont({
  src: [
    {
      path: "../../public/fonts/Gotham-Black.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gotham-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-custom",
  display: "swap",
});
export const metadata = {
  title: "Dilpasand",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${customFont.variable} font-custom antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
