import localFont from "next/font/local";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const customFont = localFont({
  src: [
    {
      path: "../../public/fonts/Gill Sans.otf", // Path to Gill Sans for paragraphs
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Futura Bold.ttf", // Path to Futura Bold for headings
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-custom",
  display: "swap",
});
export const metadata = {
  title: "Dilpasand",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${customFont.variable} font-custom antialiased`}>
        {children}
      </body>
    </html>
  );
}
